/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

--5. MAGNITUDE ANALYSIS
--Find total customers by country
SELECT 
country,
COUNT(customer_key) as total_customers
FROM Gold.dim_customers
GROUP BY country
ORDER BY COUNT(customer_key) DESC
--Find total customers by gender
SELECT gender,
COUNT(customer_key) AS [Nr.customers]
FROM Gold.dim_customers
GROUP BY gender
ORDER BY [Nr.customers] DESC

--Find total products by category
SELECT 
category,
COUNT(product_name) AS total_products
FROM Gold.dim_products
GROUP BY category
ORDER BY total_products DESC
--What is the average costs in each category?
SELECT category,
AVG(product_cost) AS avgcost
FROM Gold.dim_products
GROUP BY category
--What  is the total revenue generated for each category?
SELECT
p.category,
SUM(s.sales_amount) AS total_revenue
FROM Gold.fact_sales s
LEFT JOIN Gold.dim_products P
ON P.product_key = S.product_key
GROUP BY p.category

--Find total revenue is generated by each customer
SELECT 
c.customer_key,
SUM(s.sales_amount) as total_customer_revenue
FROM Gold.fact_sales s
LEFT JOIN Gold.dim_customers c
ON c.customer_key = s.customer_key
GROUP BY c.customer_key
ORDER BY SUM(s.sales_amount) DESC
--What is the distribution of sold items across countries?
SELECT
c.country,
SUM(s.quantity) as sold_items
FROM Gold.dim_customers c 
RIGHT JOIN Gold.fact_sales s
ON C.customer_key = s.customer_key
GROUP BY c.country
